### ISSUE TITLE
Problem when launching perception_tags.launch

### ISSUE THREAD

**Issue by YannickRiou** [LAAS-HRI/dt_uwds3_scripts#2]
```
yriou@tully:exp_director_task$ roslaunch dt_uwds3_scripts perception_tags.launch
... logging to /home/yriou/.ros/log/39172bbc-017f-11eb-ab6e-001517ebc2fd/roslaunch-tully-7767.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://140.93.7.241:34439/

SUMMARY
========

PARAMETERS
 * /ar_perception/global_frame_id: base_footprint
 * /ar_perception/publish_tf: True
 * /ar_perception/publish_viz: True
 * /ar_perception/rgb_camera_info_topic: kinect2/qhd/camer...
 * /rosdistro: kinetic
 * /rosversion: 1.12.16

NODES
  /
    ar_perception (dt_uwds3_scripts/ar_perception_node.py)

ROS_MASTER_URI=http://maxc1:11311

process[ar_perception-1]: started with pid [7792]
[ERROR] [1601294694.422870]: bad callback: <bound method ArPerceptionNode.observation_callback of <__main__.ArPerceptionNode object at 0x7fbb01a3f310>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/yriou/PR2/ws_mtc_test/src/dt_uwds3_scripts/scripts/ar_perception_node.py", line 104, in observation_callback
    id = self.id_link[marker.id]
KeyError: 104
```

**Comment by YannickRiou** [comment]
Problem coming from how id were defined in ontology
